### PR TITLE
Added column widths to settings and reworked SB css

### PR DESCRIPTION
**Pull request by MikeEsteves**
I reworked the way the css works. I think its better this way. You guys can decided. I think that it needs to use radio buttons though. (You'll see what I mean) I however couldn't work out how to use them with the config properly so left it for someone with more experience. Hope you like the changes.

### CODE REVIEW

**Comment by gugahoi** [comment]
This doesn't seem to be working for me. Are you sure this is right?

**Comment by MikeEsteves** [comment]
I'll double check. What isn't working exactly?

**Comment by MikeEsteves** [comment]
Seems to be working fine for me..

**Comment by MikeEsteves** [comment]
Made some changes. If-then statements are more adaptable and radio buttons should work. Works perfectly for me.

**Pull request closed without merging**
